### ISSUE TITLE
Incorrect path in a few places

### ISSUE THREAD

**Issue by laurie-wrisk** [TheArtling/intercom-conversations-export#1]
Thank you very much for making this package, it's been very useful.  Just noticed the paths appear to need altering in a few places in `./intercom_conversations_export/fetcher.py`. 

**Line 37**
Current: `path = os.path.join(OUTPUT_PATH, 'conversation_pages', f"page_{page}.json")`
Required: `path = os.path.join(OUTPUT_PATH, 'raw_data', 'conversation_pages', f"page_{page}.json")`

**Line 103**
Current: `directory = os.path.join(OUTPUT_PATH, 'conversation_pages')`
Required: `directory = os.path.join(OUTPUT_PATH, 'raw_data', 'conversation_pages')`

**Line 112**
Current: `path = os.path.join(OUTPUT_PATH, 'conversations', f"id_{id}.json")`
Required: `path = os.path.join(OUTPUT_PATH, 'raw_data', 'single_conversations', f"id_{id}.json")`

**Comment by assembledadam** [comment]
Nice one. Added in my PR.

**Comment by mbrochh** [comment]
Wow, very cool to see that someone else found this tool helpful!

I have merged the fixes, many thanks to both of you @assembledadam @laurie-wrisk!
